'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.261.
'
Namespace com.getsubtitle.api
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="searchSubtitles_wsdlBinding", [Namespace]:="http://173.242.116.50/~admin/nusoap"),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(Language)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(SubtitleArchive)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(SubtitleDownload)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(findSubtitleFile)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(SubtitleFile)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(Subtitle))>  _
    Partial Public Class searchSubtitles_wsdl
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private searchSubtitlesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private searchSubtitlesByHashOperationCompleted As System.Threading.SendOrPostCallback
        
        Private findSubtitlesByHashOperationCompleted As System.Threading.SendOrPostCallback
        
        Private downloadSubtitlesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getLanguagesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private uploadSubtitleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private uploadSubtitle2OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.mediastationx.My.MySettings.Default.mediastationx_com_getsubtitle_api_searchSubtitles_wsdl
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event searchSubtitlesCompleted As searchSubtitlesCompletedEventHandler
        
        '''<remarks/>
        Public Event searchSubtitlesByHashCompleted As searchSubtitlesByHashCompletedEventHandler
        
        '''<remarks/>
        Public Event findSubtitlesByHashCompleted As findSubtitlesByHashCompletedEventHandler
        
        '''<remarks/>
        Public Event downloadSubtitlesCompleted As downloadSubtitlesCompletedEventHandler
        
        '''<remarks/>
        Public Event getLanguagesCompleted As getLanguagesCompletedEventHandler
        
        '''<remarks/>
        Public Event uploadSubtitleCompleted As uploadSubtitleCompletedEventHandler
        
        '''<remarks/>
        Public Event uploadSubtitle2Completed As uploadSubtitle2CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("searchSubtitles_wsdl#searchSubtitles", RequestNamespace:="searchSubtitles_wsdl", ResponseNamespace:="searchSubtitles_wsdl")>  _
        Public Function searchSubtitles(ByVal query As String, ByVal language As String, ByVal index As Integer, ByVal count As Integer) As <System.Xml.Serialization.SoapElementAttribute("return")> Subtitle()
            Dim results() As Object = Me.Invoke("searchSubtitles", New Object() {query, language, index, count})
            Return CType(results(0),Subtitle())
        End Function
        
        '''<remarks/>
        Public Overloads Sub searchSubtitlesAsync(ByVal query As String, ByVal language As String, ByVal index As Integer, ByVal count As Integer)
            Me.searchSubtitlesAsync(query, language, index, count, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub searchSubtitlesAsync(ByVal query As String, ByVal language As String, ByVal index As Integer, ByVal count As Integer, ByVal userState As Object)
            If (Me.searchSubtitlesOperationCompleted Is Nothing) Then
                Me.searchSubtitlesOperationCompleted = AddressOf Me.OnsearchSubtitlesOperationCompleted
            End If
            Me.InvokeAsync("searchSubtitles", New Object() {query, language, index, count}, Me.searchSubtitlesOperationCompleted, userState)
        End Sub
        
        Private Sub OnsearchSubtitlesOperationCompleted(ByVal arg As Object)
            If (Not (Me.searchSubtitlesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent searchSubtitlesCompleted(Me, New searchSubtitlesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("searchSubtitlesByHash_wsdl#searchSubtitlesByHash", RequestNamespace:="searchSubtitlesByHash_wsdl", ResponseNamespace:="searchSubtitlesByHash_wsdl")>  _
        Public Function searchSubtitlesByHash(ByVal hash As String, ByVal language As String, ByVal index As Integer, ByVal count As Integer) As <System.Xml.Serialization.SoapElementAttribute("return")> SubtitleFile()
            Dim results() As Object = Me.Invoke("searchSubtitlesByHash", New Object() {hash, language, index, count})
            Return CType(results(0),SubtitleFile())
        End Function
        
        '''<remarks/>
        Public Overloads Sub searchSubtitlesByHashAsync(ByVal hash As String, ByVal language As String, ByVal index As Integer, ByVal count As Integer)
            Me.searchSubtitlesByHashAsync(hash, language, index, count, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub searchSubtitlesByHashAsync(ByVal hash As String, ByVal language As String, ByVal index As Integer, ByVal count As Integer, ByVal userState As Object)
            If (Me.searchSubtitlesByHashOperationCompleted Is Nothing) Then
                Me.searchSubtitlesByHashOperationCompleted = AddressOf Me.OnsearchSubtitlesByHashOperationCompleted
            End If
            Me.InvokeAsync("searchSubtitlesByHash", New Object() {hash, language, index, count}, Me.searchSubtitlesByHashOperationCompleted, userState)
        End Sub
        
        Private Sub OnsearchSubtitlesByHashOperationCompleted(ByVal arg As Object)
            If (Not (Me.searchSubtitlesByHashCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent searchSubtitlesByHashCompleted(Me, New searchSubtitlesByHashCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("findSubtitlesByHash_wsdl#findSubtitlesByHash", RequestNamespace:="findSubtitlesByHash_wsdl", ResponseNamespace:="findSubtitlesByHash_wsdl")>  _
        Public Function findSubtitlesByHash(ByVal hash As String, ByVal language As String, ByVal index As Integer, ByVal count As Integer) As <System.Xml.Serialization.SoapElementAttribute("return")> findSubtitleFile()
            Dim results() As Object = Me.Invoke("findSubtitlesByHash", New Object() {hash, language, index, count})
            Return CType(results(0),findSubtitleFile())
        End Function
        
        '''<remarks/>
        Public Overloads Sub findSubtitlesByHashAsync(ByVal hash As String, ByVal language As String, ByVal index As Integer, ByVal count As Integer)
            Me.findSubtitlesByHashAsync(hash, language, index, count, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub findSubtitlesByHashAsync(ByVal hash As String, ByVal language As String, ByVal index As Integer, ByVal count As Integer, ByVal userState As Object)
            If (Me.findSubtitlesByHashOperationCompleted Is Nothing) Then
                Me.findSubtitlesByHashOperationCompleted = AddressOf Me.OnfindSubtitlesByHashOperationCompleted
            End If
            Me.InvokeAsync("findSubtitlesByHash", New Object() {hash, language, index, count}, Me.findSubtitlesByHashOperationCompleted, userState)
        End Sub
        
        Private Sub OnfindSubtitlesByHashOperationCompleted(ByVal arg As Object)
            If (Not (Me.findSubtitlesByHashCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent findSubtitlesByHashCompleted(Me, New findSubtitlesByHashCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("downloadSubtitles_wsdl#downloadSubtitles", RequestNamespace:="downloadSubtitles_wsdl", ResponseNamespace:="downloadSubtitles_wsdl")>  _
        Public Function downloadSubtitles(ByVal subtitles() As SubtitleDownload, ByVal compress As Integer) As <System.Xml.Serialization.SoapElementAttribute("return")> SubtitleArchive()
            Dim results() As Object = Me.Invoke("downloadSubtitles", New Object() {subtitles, compress})
            Return CType(results(0),SubtitleArchive())
        End Function
        
        '''<remarks/>
        Public Overloads Sub downloadSubtitlesAsync(ByVal subtitles() As SubtitleDownload, ByVal compress As Integer)
            Me.downloadSubtitlesAsync(subtitles, compress, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub downloadSubtitlesAsync(ByVal subtitles() As SubtitleDownload, ByVal compress As Integer, ByVal userState As Object)
            If (Me.downloadSubtitlesOperationCompleted Is Nothing) Then
                Me.downloadSubtitlesOperationCompleted = AddressOf Me.OndownloadSubtitlesOperationCompleted
            End If
            Me.InvokeAsync("downloadSubtitles", New Object() {subtitles, compress}, Me.downloadSubtitlesOperationCompleted, userState)
        End Sub
        
        Private Sub OndownloadSubtitlesOperationCompleted(ByVal arg As Object)
            If (Not (Me.downloadSubtitlesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent downloadSubtitlesCompleted(Me, New downloadSubtitlesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("getLanguages_wsdl#getLanguages", RequestNamespace:="getLanguages_wsdl", ResponseNamespace:="getLanguages_wsdl")>  _
        Public Function getLanguages() As <System.Xml.Serialization.SoapElementAttribute("return")> Language()
            Dim results() As Object = Me.Invoke("getLanguages", New Object(-1) {})
            Return CType(results(0),Language())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getLanguagesAsync()
            Me.getLanguagesAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getLanguagesAsync(ByVal userState As Object)
            If (Me.getLanguagesOperationCompleted Is Nothing) Then
                Me.getLanguagesOperationCompleted = AddressOf Me.OngetLanguagesOperationCompleted
            End If
            Me.InvokeAsync("getLanguages", New Object(-1) {}, Me.getLanguagesOperationCompleted, userState)
        End Sub
        
        Private Sub OngetLanguagesOperationCompleted(ByVal arg As Object)
            If (Not (Me.getLanguagesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getLanguagesCompleted(Me, New getLanguagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("uploadSubtitle_wsdl#uploadSubtitle", RequestNamespace:="uploadSubtitle_wsdl", ResponseNamespace:="uploadSubtitle_wsdl")>  _
        Public Function uploadSubtitle(ByVal movieHash As String, ByVal movieByteSize As Single, ByVal subtitle As String, ByVal format As String, ByVal fileName As String, ByVal fps As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("uploadSubtitle", New Object() {movieHash, movieByteSize, subtitle, format, fileName, fps})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub uploadSubtitleAsync(ByVal movieHash As String, ByVal movieByteSize As Single, ByVal subtitle As String, ByVal format As String, ByVal fileName As String, ByVal fps As String)
            Me.uploadSubtitleAsync(movieHash, movieByteSize, subtitle, format, fileName, fps, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub uploadSubtitleAsync(ByVal movieHash As String, ByVal movieByteSize As Single, ByVal subtitle As String, ByVal format As String, ByVal fileName As String, ByVal fps As String, ByVal userState As Object)
            If (Me.uploadSubtitleOperationCompleted Is Nothing) Then
                Me.uploadSubtitleOperationCompleted = AddressOf Me.OnuploadSubtitleOperationCompleted
            End If
            Me.InvokeAsync("uploadSubtitle", New Object() {movieHash, movieByteSize, subtitle, format, fileName, fps}, Me.uploadSubtitleOperationCompleted, userState)
        End Sub
        
        Private Sub OnuploadSubtitleOperationCompleted(ByVal arg As Object)
            If (Not (Me.uploadSubtitleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent uploadSubtitleCompleted(Me, New uploadSubtitleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("uploadSubtitle2_wsdl#uploadSubtitle", RequestNamespace:="uploadSubtitle2_wsdl", ResponseNamespace:="uploadSubtitle2_wsdl")>  _
        Public Function uploadSubtitle2(ByVal movieHash As String, ByVal movieByteSize As Single, ByVal subtitle As String, ByVal format As String, ByVal fileName As String, ByVal fps As String, ByVal language As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("uploadSubtitle2", New Object() {movieHash, movieByteSize, subtitle, format, fileName, fps, language})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub uploadSubtitle2Async(ByVal movieHash As String, ByVal movieByteSize As Single, ByVal subtitle As String, ByVal format As String, ByVal fileName As String, ByVal fps As String, ByVal language As String)
            Me.uploadSubtitle2Async(movieHash, movieByteSize, subtitle, format, fileName, fps, language, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub uploadSubtitle2Async(ByVal movieHash As String, ByVal movieByteSize As Single, ByVal subtitle As String, ByVal format As String, ByVal fileName As String, ByVal fps As String, ByVal language As String, ByVal userState As Object)
            If (Me.uploadSubtitle2OperationCompleted Is Nothing) Then
                Me.uploadSubtitle2OperationCompleted = AddressOf Me.OnuploadSubtitle2OperationCompleted
            End If
            Me.InvokeAsync("uploadSubtitle2", New Object() {movieHash, movieByteSize, subtitle, format, fileName, fps, language}, Me.uploadSubtitle2OperationCompleted, userState)
        End Sub
        
        Private Sub OnuploadSubtitle2OperationCompleted(ByVal arg As Object)
            If (Not (Me.uploadSubtitle2CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent uploadSubtitle2Completed(Me, New uploadSubtitle2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://173.242.116.50/~admin/nusoap")>  _
    Partial Public Class Subtitle
        
        Private cod_movieField As Integer
        
        Private titleField As String
        
        Private movie_nameField As String
        
        Private release_nameField As String
        
        Private yearField As Integer
        
        Private hashField As String
        
        Private languageField As String
        
        Private flagField As String
        
        Private formatField As String
        
        Private totalField As String
        
        Private fpsField As String
        
        Private cdsField As Integer
        
        Private post_dateField As String
        
        Private linkField As String
        
        '''<remarks/>
        Public Property cod_movie() As Integer
            Get
                Return Me.cod_movieField
            End Get
            Set
                Me.cod_movieField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property movie_name() As String
            Get
                Return Me.movie_nameField
            End Get
            Set
                Me.movie_nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property release_name() As String
            Get
                Return Me.release_nameField
            End Get
            Set
                Me.release_nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property year() As Integer
            Get
                Return Me.yearField
            End Get
            Set
                Me.yearField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property hash() As String
            Get
                Return Me.hashField
            End Get
            Set
                Me.hashField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property language() As String
            Get
                Return Me.languageField
            End Get
            Set
                Me.languageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property flag() As String
            Get
                Return Me.flagField
            End Get
            Set
                Me.flagField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property format() As String
            Get
                Return Me.formatField
            End Get
            Set
                Me.formatField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property total() As String
            Get
                Return Me.totalField
            End Get
            Set
                Me.totalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fps() As String
            Get
                Return Me.fpsField
            End Get
            Set
                Me.fpsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cds() As Integer
            Get
                Return Me.cdsField
            End Get
            Set
                Me.cdsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property post_date() As String
            Get
                Return Me.post_dateField
            End Get
            Set
                Me.post_dateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property link() As String
            Get
                Return Me.linkField
            End Get
            Set
                Me.linkField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://173.242.116.50/~admin/nusoap")>  _
    Partial Public Class Language
        
        Private cod_languageField As Integer
        
        Private languageField As String
        
        Private flagField As String
        
        Private desc_reduzidoField As String
        
        Private charsetField As String
        
        '''<remarks/>
        Public Property cod_language() As Integer
            Get
                Return Me.cod_languageField
            End Get
            Set
                Me.cod_languageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property language() As String
            Get
                Return Me.languageField
            End Get
            Set
                Me.languageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property flag() As String
            Get
                Return Me.flagField
            End Get
            Set
                Me.flagField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property desc_reduzido() As String
            Get
                Return Me.desc_reduzidoField
            End Get
            Set
                Me.desc_reduzidoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property charset() As String
            Get
                Return Me.charsetField
            End Get
            Set
                Me.charsetField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://173.242.116.50/~admin/nusoap")>  _
    Partial Public Class SubtitleArchive
        
        Private cod_subtitle_fileField As Integer
        
        Private dataField As String
        
        '''<remarks/>
        Public Property cod_subtitle_file() As Integer
            Get
                Return Me.cod_subtitle_fileField
            End Get
            Set
                Me.cod_subtitle_fileField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property data() As String
            Get
                Return Me.dataField
            End Get
            Set
                Me.dataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://173.242.116.50/~admin/nusoap")>  _
    Partial Public Class SubtitleDownload
        
        Private movie_hashField As String
        
        Private cod_subtitle_fileField As Integer
        
        '''<remarks/>
        Public Property movie_hash() As String
            Get
                Return Me.movie_hashField
            End Get
            Set
                Me.movie_hashField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cod_subtitle_file() As Integer
            Get
                Return Me.cod_subtitle_fileField
            End Get
            Set
                Me.cod_subtitle_fileField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://173.242.116.50/~admin/nusoap")>  _
    Partial Public Class findSubtitleFile
        
        Private subtitle_hashField As String
        
        Private formatField As String
        
        Private file_nameField As String
        
        Private upload_countField As Integer
        
        Private download_countField As Integer
        
        Private post_dateField As String
        
        Private linkField As String
        
        Private totalField As Integer
        
        Private fpsField As String
        
        Private imdbField As Integer
        
        Private cod_languageField As Integer
        
        '''<remarks/>
        Public Property subtitle_hash() As String
            Get
                Return Me.subtitle_hashField
            End Get
            Set
                Me.subtitle_hashField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property format() As String
            Get
                Return Me.formatField
            End Get
            Set
                Me.formatField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property file_name() As String
            Get
                Return Me.file_nameField
            End Get
            Set
                Me.file_nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property upload_count() As Integer
            Get
                Return Me.upload_countField
            End Get
            Set
                Me.upload_countField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property download_count() As Integer
            Get
                Return Me.download_countField
            End Get
            Set
                Me.download_countField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property post_date() As String
            Get
                Return Me.post_dateField
            End Get
            Set
                Me.post_dateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property link() As String
            Get
                Return Me.linkField
            End Get
            Set
                Me.linkField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property total() As Integer
            Get
                Return Me.totalField
            End Get
            Set
                Me.totalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fps() As String
            Get
                Return Me.fpsField
            End Get
            Set
                Me.fpsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property imdb() As Integer
            Get
                Return Me.imdbField
            End Get
            Set
                Me.imdbField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cod_language() As Integer
            Get
                Return Me.cod_languageField
            End Get
            Set
                Me.cod_languageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://173.242.116.50/~admin/nusoap")>  _
    Partial Public Class SubtitleFile
        
        Private file_nameField As String
        
        Private post_dateField As String
        
        Private languageField As String
        
        Private desc_reduzidoField As String
        
        Private sub_hashField As String
        
        Private cod_subtitle_fileField As Integer
        
        '''<remarks/>
        Public Property file_name() As String
            Get
                Return Me.file_nameField
            End Get
            Set
                Me.file_nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property post_date() As String
            Get
                Return Me.post_dateField
            End Get
            Set
                Me.post_dateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property language() As String
            Get
                Return Me.languageField
            End Get
            Set
                Me.languageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property desc_reduzido() As String
            Get
                Return Me.desc_reduzidoField
            End Get
            Set
                Me.desc_reduzidoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property sub_hash() As String
            Get
                Return Me.sub_hashField
            End Get
            Set
                Me.sub_hashField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cod_subtitle_file() As Integer
            Get
                Return Me.cod_subtitle_fileField
            End Get
            Set
                Me.cod_subtitle_fileField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub searchSubtitlesCompletedEventHandler(ByVal sender As Object, ByVal e As searchSubtitlesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class searchSubtitlesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Subtitle()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Subtitle())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub searchSubtitlesByHashCompletedEventHandler(ByVal sender As Object, ByVal e As searchSubtitlesByHashCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class searchSubtitlesByHashCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SubtitleFile()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SubtitleFile())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub findSubtitlesByHashCompletedEventHandler(ByVal sender As Object, ByVal e As findSubtitlesByHashCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class findSubtitlesByHashCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As findSubtitleFile()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),findSubtitleFile())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub downloadSubtitlesCompletedEventHandler(ByVal sender As Object, ByVal e As downloadSubtitlesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class downloadSubtitlesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SubtitleArchive()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SubtitleArchive())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub getLanguagesCompletedEventHandler(ByVal sender As Object, ByVal e As getLanguagesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getLanguagesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Language()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Language())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub uploadSubtitleCompletedEventHandler(ByVal sender As Object, ByVal e As uploadSubtitleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class uploadSubtitleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub uploadSubtitle2CompletedEventHandler(ByVal sender As Object, ByVal e As uploadSubtitle2CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class uploadSubtitle2CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
